### ISSUE TITLE
please tell me the pin assignment

### ISSUE THREAD

**Issue by nanigasi-san** [KonssnoK/py-bh1792glc#1]
Hello!
I am so happy thanks to your technology!

I need to use bh1792glc on Raspberry Pi 3B +. I found this repository without any information!

Unfortunately, I am new to the circuit, so I don't know what to do with pin assignments ...

And the product expires the day after tomorrow!

Could you please give me a reference pin layout for me?

Kaito.

**Comment by KonssnoK** [comment]
Hi there,
you can check the pinout here
https://www.raspberrypi-spy.co.uk/2014/07/raspberry-pi-b-gpio-header-details-and-pinout/


By the default the example uses I2C1 and GPIO17 for the interrupts
(Pins 3 5, int on 11, 6/9 for ground and pin 1 for 3.3)

**Comment by nanigasi-san** [comment]
Hi Mr.KonssoK!!
This was very useful information for me!

Thank you for answering while busy! !

**Comment by KonssnoK** [comment]
no problem, have a nice day :)
